//! Semantic + Keyword Search Command (Commit 6).
//!
//! Merges standard SQLite FTS (LIKE) with an in-memory vector KNN using
//! cosine similarity over the embeddings generated by our StubEmbedder.

use std::cmp::Ordering;
use tauri::State;
use crate::import::{AppState, AssetData};

#[derive(serde::Serialize)]
pub struct SearchResult {
    #[serde(flatten)]
    pub asset: AssetData,
    pub score: f32,
    pub is_semantic: bool,
    pub document_title: Option<String>,
}

#[tauri::command]
pub fn search_assets(
    query: String,
    limit: usize,
    state: State<'_, AppState>,
) -> Result<Vec<SearchResult>, String> {
    let db_lock = state.db.lock().unwrap();
    let conn = db_lock.as_ref().ok_or("No vault opened")?;

    let lower_query = format!("%{}%", query.to_lowercase());

    // 1. Keyword search (score = 1.0)
    let mut keyword_results = std::collections::HashMap::new();
    
    let sql = "
        SELECT a.id, a.title, a.filename, a.filepath, a.type, a.size, a.width, a.height, a.favorite,
               a.date_added, a.url, a.notes, a.archived, a.trashed, a.palette, a.color_profile,
               a.folder_id, a.thumbnail_url, a.document_id, a.page_number, a.page_text, a.status,
               d.title as doc_title
        FROM assets a
        LEFT JOIN documents d ON a.document_id = d.id
        LEFT JOIN asset_tags at ON a.id = at.asset_id
        LEFT JOIN tags t ON at.tag_id = t.id
        WHERE lower(a.title) LIKE ?1
           OR lower(a.filename) LIKE ?1
           OR lower(a.page_text) LIKE ?1
           OR lower(t.name) LIKE ?1
        GROUP BY a.id
    ";

    if let Ok(mut stmt) = conn.prepare(sql) {
        if let Ok(rows) = stmt.query_map([&lower_query], |row| {
            let id: String = row.get(0)?;
            let doc_title: Option<String> = row.get(22)?;
            let asset = AssetData {
                id: id.clone(),
                title: row.get(1)?,
                filename: row.get(2)?,
                filepath: row.get(3)?,
                type_: row.get(4)?,
                size: row.get(5)?,
                width: row.get(6)?,
                height: row.get(7)?,
                favorite: row.get(8)?,
                date_added: row.get(9)?,
                url: row.get(10)?,
                notes: row.get(11)?,
                archived: row.get(12)?,
                trashed: row.get(13)?,
                palette: row.get::<_, Option<String>>(14)?.and_then(|s| serde_json::from_str(&s).ok()),
                color_profile: row.get(15)?,
                tags: vec![], // Populate later if needed
                collections: vec![],
                folder_id: row.get(16)?,
                thumbnail_url: row.get(17)?,
            };
            Ok((id, asset, doc_title))
        }) {
            for row_res in rows {
                if let Ok((id, asset, doc_title)) = row_res {
                    keyword_results.insert(id.clone(), SearchResult {
                        asset,
                        score: 1.0,
                        is_semantic: false,
                        document_title: doc_title,
                    });
                }
            }
        }
    }

    // 2. Semantic search
    let embedder = crate::ai::embedder::StubEmbedder;
    let query_emb = crate::ai::embedder::Embedder::embed_text(&embedder, &query);
    
    let mut semantic_scores = Vec::new();

    if let Ok(mut stmt) = conn.prepare("SELECT asset_id, text_embedding FROM asset_embeddings WHERE text_embedding IS NOT NULL") {
        if let Ok(mut rows) = stmt.query([]) {
            while let Ok(Some(row)) = rows.next() {
                let asset_id: String = row.get(0).unwrap();
                let blob: Vec<u8> = row.get(1).unwrap();
                
                // Decode little-endian f32s
                let mut emb = Vec::with_capacity(blob.len() / 4);
                for chunk in blob.chunks_exact(4) {
                    let mut b = [0u8; 4];
                    b.copy_from_slice(chunk);
                    emb.push(f32::from_le_bytes(b));
                }

                // Cosine similarity
                let dot_product: f32 = query_emb.iter().zip(emb.iter()).map(|(a, b)| a * b).sum();
                if dot_product > 0.5 { // Arbitrary threshold for demo
                    semantic_scores.push((asset_id, dot_product));
                }
            }
        }
    }

    // Load semantic winners
    for (asset_id, score) in semantic_scores {
        if !keyword_results.contains_key(&asset_id) {
            let sql2 = "
                SELECT a.id, a.title, a.filename, a.filepath, a.type, a.size, a.width, a.height, a.favorite,
                       a.date_added, a.url, a.notes, a.archived, a.trashed, a.palette, a.color_profile,
                       a.folder_id, a.thumbnail_url, d.title as doc_title
                FROM assets a
                LEFT JOIN documents d ON a.document_id = d.id
                WHERE a.id = ?1
            ";
            if let Ok(mut stmt) = conn.prepare(sql2) {
                if let Ok(mut rows) = stmt.query([&asset_id]) {
                    if let Ok(Some(row)) = rows.next() {
                        let doc_title: Option<String> = row.get(18).unwrap_or(None);
                        let asset = AssetData {
                            id: row.get(0).unwrap(),
                            title: row.get(1).unwrap(),
                            filename: row.get(2).unwrap(),
                            filepath: row.get(3).unwrap(),
                            type_: row.get(4).unwrap(),
                            size: row.get(5).unwrap(),
                            width: row.get(6).unwrap(),
                            height: row.get(7).unwrap(),
                            favorite: row.get(8).unwrap(),
                            date_added: row.get(9).unwrap(),
                            url: row.get(10).unwrap(),
                            notes: row.get(11).unwrap_or(None),
                            archived: row.get(12).unwrap(),
                            trashed: row.get(13).unwrap(),
                            palette: row.get::<_, Option<String>>(14).ok().flatten().and_then(|s| serde_json::from_str(&s).ok()),
                            color_profile: row.get(15).unwrap_or(None),
                            tags: vec![],
                            collections: vec![],
                            folder_id: row.get(16).unwrap_or(None),
                            thumbnail_url: row.get(17).unwrap_or(None),
                        };
                        keyword_results.insert(asset_id.clone(), SearchResult {
                            asset,
                            score,
                            is_semantic: true,
                            document_title: doc_title,
                        });
                    }
                }
            }
        } else {
            // Already matched by keyword, just boost score
            if let Some(res) = keyword_results.get_mut(&asset_id) {
                res.score += score;
            }
        }
    }

    // 3. Sort and limit
    let mut final_results: Vec<SearchResult> = keyword_results.into_values().collect();
    final_results.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(Ordering::Equal));
    final_results.truncate(limit);

    Ok(final_results)
}
